import { Doc, P, ref } from "tskb";

const SkillGenModule = ref as tskb.Modules["cli.utils.skill-generator"];
const ContentBuilderModule = ref as tskb.Modules["cli.utils.content-builder"];

export default (
  <Doc explains="How are the .claude/skills/ files maintained?" priority="constraint">
    <P>
      Every file under `.claude/skills/tskb*/` — both `SKILL.md` and any `references/*.md` — is
      generated by the docs build. Hand edits to those files are overwritten on the next run, so
      treat the generated tree as build output, not source.
    </P>
    <P>
      The source of truth lives in two modules. {ContentBuilderModule} owns the markdown bodies:
      skill prose, the reference-file contents, and the Copilot instructions. {SkillGenModule}
      writes those bodies to disk, including the frontmatter (name, description, allowed-tools) and
      the per-skill `references/` directory. To change a skill's content, frontmatter, or its set of
      references, edit one of those two modules and rebuild — never the generated Markdown.
    </P>
  </Doc>
);
